### ISSUE TITLE
Typo in install instruction

### ISSUE THREAD

**Issue by yeboahnanaosei** [samuelships/harlot#1]
It appears you have a typo in the installation section of your readme.
You have: `git clone https://github.com/yourusername/harlot.git`. 
Notice `/yourusername/` in the path? 
I guess it should be: `git clone https://github.com/samuelships/harlot.git`.

Also any Go developer can easily install your tool without cloning the repo.  
The `go` command makes it easy: `go install github.com/samuelships/harlot@latest`

**Comment by samuelships** [comment]
fixed :)
